### ISSUE TITLE
Node 8 image

### ISSUE THREAD

**Issue by nk2580** [tarampampam/node-docker#3]
Can we make a branch for node 8, this LTS is still heavily supported and is quite widespread in terms of use due to AWS Lambda

**Comment by tarampampam** [comment]
@nk2580 ready:

- https://github.com/tarampampam/node-docker/tree/image-9-alpine `tarampampam/node:8-alpine`
- https://github.com/tarampampam/node-docker/tree/image-8-alpine `tarampampam/node:9-alpine`

This images will be time-to-time rebuilded, so, any insalled software shoul have actial versions.
